server:
 port: 8080
 servlet:
  encoding:
   charset: UTF-8
   
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    doc-expansion: none # tag, operation 펼치는 방식

 
spring:
 datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:~/jobis
  username: sa
  password:
 h2:
  console:
   enabled: true
   path: /h2-console
 sql:
  init:
   mode: always
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  defer-datasource-initialization: true
  show-sql: true
  hibernate:
   ddl-auto: create
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER

